version: '2'

services:
  pyspark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./rawdata:/rawdata
      - ./pipelinedata:/pipelinedata
      - ./python:/python
